kind: role
version: v5
metadata:
  name: admin
spec:
  allow:
    logins: ['root']
    node_labels:
      '*': '*'
    rules:
      - resources: ['*']
        verbs: ['*']
  options:
    max_session_ttl: 4h
    forward_agent: false
