kind: role
version: v5
metadata:
  name: operator
spec:
  allow:
    logins: ['root']
    node_labels:
      env: production
    request:
      roles: ['admin']
  options:
    max_session_ttl: 8h
    forward_agent: false
