#!/usr/bin/env python3
"""Sync scanner findings into the auto-generated POA&M ledger.

Phase 20.1-04 task 2: the POA&M stops being a hand-curated document. This
script parses Trivy (SARIF), Checkov (JSON), and Gitleaks (JSON) output into
ledger rows, deduplicated by fingerprint, so running it twice on the same
input is a no-op and a new finding appears as exactly one new row.

Ledger: docs/grc/POAM_AUTO_FINDINGS.md (fully script-owned; hand edits are
overwritten). The curated register in POAM_PLAN_OF_ACTION.md is unchanged:
rows graduate there only when a human triages them, which is the point of
the split. Machines maintain the intake queue, humans own the decisions.

Fingerprint = sha256(source|rule|location)[:12]. Stable across reruns and
across line-number churn for Trivy/Checkov (location excludes line); Gitleaks
keeps the line because two secrets in one file are two findings.

Usage:
  python3 scripts/poam_sync.py [--trivy f.sarif] [--checkov f.json]
                               [--gitleaks f.json] [--date YYYY-MM-DD]

A source's absent findings auto-close ONLY when that source's file is passed
in the same run (no scan means no evidence either way).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEDGER = REPO_ROOT / "docs" / "grc" / "POAM_AUTO_FINDINGS.md"

HEADER = """# POA&M Auto Findings Ledger

Script-generated by `scripts/poam_sync.py`. Do not hand-edit: rows are owned
by the scanners. Triaged findings graduate to `POAM_PLAN_OF_ACTION.md` with
compensating controls and milestones; this file is the raw intake queue.

| ID | Fingerprint | Source | Severity | Rule | Location | First seen | Last seen | Status |
|----|-------------|--------|----------|------|----------|------------|-----------|--------|
"""

ROW_RE = re.compile(
    r"^\|\s*(POAM-AUTO-\d+)\s*\|\s*([0-9a-f]{12})\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*"
    r"\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|$"
)


def fingerprint(source: str, rule: str, location: str) -> str:
    return hashlib.sha256(f"{source}|{rule}|{location}".encode()).hexdigest()[:12]


def parse_trivy(path: Path) -> list[dict]:
    """Trivy SARIF: one finding per result, located by artifact URI."""
    sarif = json.loads(path.read_text())
    out = []
    for run in sarif.get("runs", []):
        rules = {
            r["id"]: r
            for r in run.get("tool", {}).get("driver", {}).get("rules", [])
        }
        for res in run.get("results", []):
            rule = res.get("ruleId", "unknown")
            sev = (
                rules.get(rule, {})
                .get("properties", {})
                .get("security-severity", "")
            )
            level = res.get("level", "warning")
            severity = (
                "CRITICAL" if sev and float(sev) >= 9.0
                else "HIGH" if sev and float(sev) >= 7.0
                else level.upper()
            )
            loc = "unknown"
            locs = res.get("locations", [])
            if locs:
                loc = (
                    locs[0]
                    .get("physicalLocation", {})
                    .get("artifactLocation", {})
                    .get("uri", "unknown")
                )
            out.append(
                {"source": "trivy", "rule": rule, "location": loc, "severity": severity}
            )
    return out


def parse_checkov(path: Path) -> list[dict]:
    """Checkov JSON (single framework object or list of them)."""
    data = json.loads(path.read_text())
    frameworks = data if isinstance(data, list) else [data]
    out = []
    for fw in frameworks:
        for chk in fw.get("results", {}).get("failed_checks", []):
            loc = f"{chk.get('file_path', 'unknown')}:{chk.get('resource', '')}"
            out.append(
                {
                    "source": "checkov",
                    "rule": chk.get("check_id", "unknown"),
                    "location": loc,
                    "severity": (chk.get("severity") or "UNSCORED").upper(),
                }
            )
    return out


def parse_gitleaks(path: Path) -> list[dict]:
    """Gitleaks JSON report. Line number kept: two secrets in one file differ."""
    data = json.loads(path.read_text())
    return [
        {
            "source": "gitleaks",
            "rule": f.get("RuleID", "unknown"),
            "location": f"{f.get('File', 'unknown')}:{f.get('StartLine', 0)}",
            "severity": "HIGH",
        }
        for f in data
    ]


def load_ledger() -> list[dict]:
    if not LEDGER.exists():
        return []
    rows = []
    for line in LEDGER.read_text().splitlines():
        m = ROW_RE.match(line)
        if m:
            keys = (
                "id", "fp", "source", "severity", "rule",
                "location", "first_seen", "last_seen", "status",
            )
            rows.append(dict(zip(keys, (g.strip() for g in m.groups()))))
    return rows


def write_ledger(rows: list[dict]) -> None:
    rows = sorted(rows, key=lambda r: int(r["id"].rsplit("-", 1)[1]))
    lines = [
        f"| {r['id']} | {r['fp']} | {r['source']} | {r['severity']} | {r['rule']} "
        f"| {r['location']} | {r['first_seen']} | {r['last_seen']} | {r['status']} |"
        for r in rows
    ]
    LEDGER.write_text(HEADER + "\n".join(lines) + ("\n" if lines else ""))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--trivy", type=Path)
    ap.add_argument("--checkov", type=Path)
    ap.add_argument("--gitleaks", type=Path)
    ap.add_argument("--date", default=date.today().isoformat())
    args = ap.parse_args()

    scanned: dict[str, list[dict]] = {}
    if args.trivy:
        scanned["trivy"] = parse_trivy(args.trivy)
    if args.checkov:
        scanned["checkov"] = parse_checkov(args.checkov)
    if args.gitleaks:
        scanned["gitleaks"] = parse_gitleaks(args.gitleaks)
    if not scanned:
        print("nothing to do: pass at least one of --trivy/--checkov/--gitleaks")
        return 1

    rows = load_ledger()
    by_fp = {r["fp"]: r for r in rows}
    next_id = 1 + max((int(r["id"].rsplit("-", 1)[1]) for r in rows), default=0)
    added = updated = closed = 0

    seen_fps: dict[str, set[str]] = {src: set() for src in scanned}
    for src, findings in scanned.items():
        for f in findings:
            fp = fingerprint(f["source"], f["rule"], f["location"])
            seen_fps[src].add(fp)
            if fp in by_fp:
                row = by_fp[fp]
                row["last_seen"] = args.date
                if row["status"] == "Closed":  # regression: it came back
                    row["status"] = "Open"
                updated += 1
            else:
                by_fp[fp] = {
                    "id": f"POAM-AUTO-{next_id:04d}",
                    "fp": fp,
                    "source": f["source"],
                    "severity": f["severity"],
                    "rule": f["rule"],
                    "location": f["location"],
                    "first_seen": args.date,
                    "last_seen": args.date,
                    "status": "Open",
                }
                next_id += 1
                added += 1

    # Auto-close: open rows from a scanned source that no longer report.
    for row in by_fp.values():
        src = row["source"]
        if src in scanned and row["status"] == "Open" and row["fp"] not in seen_fps[src]:
            row["status"] = "Closed"
            row["last_seen"] = args.date
            closed += 1

    write_ledger(list(by_fp.values()))
    total = len(by_fp)
    open_n = sum(1 for r in by_fp.values() if r["status"] == "Open")
    print(
        f"ledger: {total} rows ({open_n} open) | +{added} new, "
        f"{updated} re-seen, {closed} auto-closed | {LEDGER.relative_to(REPO_ROOT)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
