"""Squire FastAPI surface (17-09).

Endpoints:
  GET  /health          -- always 200 JSON; no auth.
  GET  /healthz         -- legacy alias for /health.
  POST /alert           -- run the graph on an incoming alert. Dual auth.
  POST /replay/{id}     -- re-run the graph on a stored alert payload.

Cross-cutting concerns wired here:
  - Auth middleware (X-Squire-Token + optional X-Internal for net-core internal path)
  - Alert dedup (criterion #18)
  - Daily cost ceiling with breach dispatch (criterion #15)
  - X-Squire-Max-Iterations header override -> graph (17-12 eval harness)
  - Citation guard middleware at boundary (criterion #17 defense-in-depth)
  - Actions allow-list enforcement (criterion #16) in recommend-only mode
  - Degraded-mode response header + footer (criterion #19)
  - Structured block-reason JSON on breach (criterion #25 scaffold)
"""
from __future__ import annotations

import json as _json
import logging
import os
import time
import uuid
from typing import Any

from fastapi import FastAPI, Header, HTTPException, Request, Response
from fastapi.responses import JSONResponse

from . import __version__
from .actions_allowlist import RecommendOnlyViolation, enforce_response as allowlist_enforce
from .api_models import AlertRequest, AlertResponse
from .citations import filter_citations
from .cost_ceiling import consult as consult_budget
from .dedup import check_and_register, update_trace_id as dedup_update_trace
from .persist import load_alert, save_investigation
from .pre_graph_pii import build_snippet as pii_snippet, scan as pii_scan
from .response_builder import build_block_response
from .settings import settings

log = logging.getLogger("squire.app")

DEGRADED_FOOTER = (
    "Degraded mode: primary LLM unreachable, response generated by local model."
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _invoke_graph(
    alert: dict[str, Any], alert_id: str, max_iters_override: int | None
) -> dict[str, Any]:
    """Lazy-import the graph so test harnesses with graph monkeypatched work."""
    from .graph import invoke_with_trace  # noqa: WPS433 (runtime import by design)

    return invoke_with_trace(
        alert, alert_id=alert_id, max_iterations_override=max_iters_override
    )


def _auth(
    token_header: str | None,
    internal_header: str | None,
    request: Request,
) -> str:
    """Raise 401 unless the bearer matches.

    When X-Internal=1 AND the client IP is in the docker bridge range, the path
    is tagged as "internal" so downstream logging can differentiate. The secret
    must still be correct in both cases -- the internal flag does NOT bypass
    the token check.
    """
    expected = settings.squire_webhook_token.get_secret_value()
    if not token_header or token_header != expected:
        raise HTTPException(status_code=401, detail="unauthorized")
    if internal_header == "1":
        client_host = request.client.host if request.client else ""
        if (
            client_host.startswith("172.")
            or client_host.startswith("127.")
            or client_host == "::1"
        ):
            return "internal"
    return "external"


def _parse_max_iters(header_val: str | None) -> int | None:
    """Parse X-Squire-Max-Iterations as an int in [0, 10]; None on failure."""
    if not header_val:
        return None
    try:
        v = int(header_val)
    except Exception:
        return None
    if 0 <= v <= 10:
        return v
    return None


def _extract_nemo_block(state: dict[str, Any]) -> dict[str, str] | None:
    """Return parsed nemo_block fields from state.errors, or None.

    Looks for ``nemo_block:reason_code=X;rail_name=Y;rule_name=Z;snippet=W``
    markers stamped by draft/critique nodes when NeMo Guardrails fires.
    """
    errors = state.get("errors") or []
    for err in errors:
        if not isinstance(err, str) or not err.startswith("nemo_block:"):
            continue
        body = err[len("nemo_block:"):]
        fields: dict[str, str] = {}
        for pair in body.split(";"):
            if "=" in pair:
                k, v = pair.split("=", 1)
                fields[k.strip()] = v
        return {
            "reason_code": fields.get("reason_code", "RAIL_BLOCK"),
            "rail_name": fields.get("rail_name", "default"),
            "rule_name": fields.get("rule_name", "unknown"),
            "input_snippet": fields.get("snippet", ""),
        }
    return None


def _build_response(
    *,
    alert_id: str,
    state: dict[str, Any],
    duration_ms: int,
    degraded_override_reason: str | None = None,
) -> AlertResponse:
    """Assemble the outward AlertResponse from a graph final-state dict.

    Runs the citation-guard + allow-list rewrite at the FastAPI boundary as
    defense-in-depth beyond the draft node's own validators. If a NeMo rail
    fired during the graph, returns a structured block response (criterion
    #25) and short-circuits the normal report assembly.
    """
    # Rail-block short-circuit (criterion #25)
    block = _extract_nemo_block(state)
    if block is not None:
        return AlertResponse(
            alert_id=alert_id,
            severity="BLOCKED",
            report=build_block_response(
                reason_code=block["reason_code"],
                rail_name=block["rail_name"],
                rule_name=block["rule_name"],
                input_snippet=block["input_snippet"],
                extra={"blocked_by": "nemo_guardrails"},
            ),
            citations={},
            trace_id=state.get("trace_id"),
            trace_url=(
                f"{settings.langfuse_host}/trace/{state.get('trace_id')}"
                if state.get("trace_id")
                else None
            ),
            duration_ms=duration_ms,
            cost_usd=float(state.get("total_cost_usd", 0.0) or 0.0),
        )

    report_raw = state.get("draft_report") or "{}"
    try:
        report = _json.loads(report_raw) if isinstance(report_raw, str) else dict(report_raw)
    except Exception:
        report = {"raw": str(report_raw)[:4000]}
    if not isinstance(report, dict):
        report = {"raw": str(report)[:4000]}

    # (citation guard: criterion #17 defense-in-depth)
    report["citations"] = filter_citations(report.get("citations", {}))

    # (allow-list rewrite: criterion #16 recommend-only)
    try:
        report = allowlist_enforce(report)
    except RecommendOnlyViolation as exc:
        # Should never fire in rewrite mode; if it does (mode=reject), surface
        # the structured block payload.
        return AlertResponse(
            alert_id=alert_id,
            severity="BLOCKED",
            report=build_block_response(
                reason_code="recommend_only_violation",
                rail_name="actions_allowlist",
                rule_name=",".join(ev.get("matched_pattern", "") for ev in exc.events),
                input_snippet=_json.dumps(report)[:400],
                extra={"events": exc.events},
            ),
            citations={},
            trace_id=state.get("trace_id"),
            trace_url=(
                f"{settings.langfuse_host}/trace/{state.get('trace_id')}"
                if state.get("trace_id")
                else None
            ),
            duration_ms=duration_ms,
            cost_usd=float(state.get("total_cost_usd", 0.0) or 0.0),
        )

    degraded = bool(state.get("_degraded_mode", False)) or bool(degraded_override_reason)
    degraded_reason = state.get("_degraded_reason") or degraded_override_reason or None
    footer = DEGRADED_FOOTER if degraded else None

    trace_id = state.get("trace_id")
    trace_url = f"{settings.langfuse_host}/trace/{trace_id}" if trace_id else None

    return AlertResponse(
        alert_id=alert_id,
        severity=state.get("severity", "UNKNOWN"),
        report=report,
        citations=report.get("citations") or state.get("citations") or {},
        trace_id=trace_id,
        trace_url=trace_url,
        duration_ms=duration_ms,
        cost_usd=float(state.get("total_cost_usd", 0.0) or 0.0),
        degraded_mode=degraded,
        degraded_reason=degraded_reason,
        footer=footer,
    )


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------


def create_app() -> FastAPI:
    app = FastAPI(
        title="Squire",
        version=__version__,
        description="Autonomous SOC analyst -- Phase 17 FastAPI surface.",
    )

    # Keycloak token connectivity check (Phase 20 / JIT-CA Gate 2 scaffold).
    # When kc_enabled=True, fetch a service-account token at startup so the
    # process fails fast on misconfiguration instead of failing on first tool
    # call. When kc_enabled=False, skip silently.
    if settings.kc_enabled:
        from .keycloak_client import KeycloakAuthError, get_kc_client
        try:
            get_kc_client().get_token()
            log.info("kc.startup.ok client_id=%s realm=%s",
                     settings.kc_client_id, settings.kc_realm)
        except KeycloakAuthError as exc:
            log.error("kc.startup.failed reason=%s", exc)
            raise

    @app.get("/health")
    def health() -> dict[str, str]:
        return {"status": "ok", "service": "squire", "version": __version__}

    @app.get("/healthz")
    def healthz() -> dict[str, str]:
        return {"status": "ok"}

    @app.post("/alert")
    def alert_endpoint(  # noqa: C901 -- high-level orchestrator, intentionally linear
        req: AlertRequest,
        request: Request,
        response: Response,
        x_squire_token: str | None = Header(default=None, alias="X-Squire-Token"),
        x_internal: str | None = Header(default=None, alias="X-Internal"),
        x_squire_max_iters: str | None = Header(
            default=None, alias="X-Squire-Max-Iterations"
        ),
    ):
        _auth(x_squire_token, x_internal, request)
        alert_id = req.alert_id or f"sq-{uuid.uuid4()}"

        # ---------------- Dedup (criterion #18) ----------------
        dedup = check_and_register(req.alert, alert_id=alert_id, trace_id=None)
        if dedup.is_duplicate:
            response.headers["X-Squire-Deduplicated"] = "true"
            return AlertResponse(
                alert_id=alert_id,
                severity="DEDUPLICATED",
                report={
                    "info": "duplicate within dedup window",
                    "original_alert_id": dedup.original_alert_id,
                },
                citations={},
                trace_id=dedup.original_trace_id,
                trace_url=(
                    f"{settings.langfuse_host}/trace/{dedup.original_trace_id}"
                    if dedup.original_trace_id
                    else None
                ),
                duration_ms=0,
                cost_usd=0.0,
                deduplicated=True,
                original_alert_id=dedup.original_alert_id,
                original_trace_id=dedup.original_trace_id,
            )

        # ---------------- Pre-graph PII scan (17-10 remediation) ----------------
        # NeMo's input rail only fronts draft + critique nodes. PII in the raw
        # alert payload can be summarised away by classify/retrieve/enrich
        # before the rail ever sees it. Red-team cases 03-04 demonstrated this
        # gap. Scanning the raw payload here closes it at sub-millisecond cost.
        pii_hit = pii_scan(req.alert)
        if pii_hit is not None:
            response.headers["X-Squire-Rail-Blocked"] = "true"
            return AlertResponse(
                alert_id=alert_id,
                severity="BLOCKED",
                report=build_block_response(
                    reason_code="PII_DETECTED_PRE_GRAPH",
                    rail_name="pre_graph",
                    rule_name=f"regex_{pii_hit.entity.lower()}",
                    input_snippet=pii_snippet(req.alert, pii_hit),
                    extra={"blocked_by": "pre_graph_pii"},
                ),
                citations={},
                trace_id=None,
                trace_url=None,
                duration_ms=0,
                cost_usd=0.0,
            )

        # ---------------- Cost ceiling (criterion #15) ----------------
        budget = consult_budget()
        if budget.breach and budget.mode == "refuse":
            return JSONResponse(
                status_code=503,
                content={
                    "error": "service_unavailable",
                    "reason_code": "daily_cost_ceiling_reached",
                    "details": {
                        "spent_today_usd": budget.spent,
                        "ceiling_usd": budget.ceiling,
                        "breach_mode": budget.mode,
                    },
                    "retry_after_seconds": 3600,
                },
                headers={"Retry-After": "3600"},
            )

        backend_override = budget.backend_override
        degraded_reason_from_budget = budget.reason if backend_override else None

        # ---------------- Graph invocation ----------------
        override_iters = _parse_max_iters(x_squire_max_iters)

        t0 = time.monotonic()
        prev_backend = os.environ.get("SQUIRE_LLM_BACKEND")
        try:
            if backend_override:
                os.environ["SQUIRE_LLM_BACKEND"] = backend_override
            state = _invoke_graph(req.alert, alert_id, override_iters)
        finally:
            if prev_backend is not None:
                os.environ["SQUIRE_LLM_BACKEND"] = prev_backend
            elif backend_override:
                os.environ.pop("SQUIRE_LLM_BACKEND", None)
        duration_ms = int((time.monotonic() - t0) * 1000)

        # ---------------- Persistence ----------------
        try:
            save_investigation(
                alert_id,
                state,
                duration_ms,
                alert_payload=req.alert,
                source=req.source or "webhook",
            )
            if state.get("trace_id"):
                dedup_update_trace(dedup.sig, state["trace_id"])
        except Exception as e:  # pragma: no cover
            log.warning("persist failed for %s: %s", alert_id, e)
            state.setdefault("errors", []).append(f"persist_failed: {e}")

        # ---------------- Degraded-mode header ----------------
        degraded = bool(state.get("_degraded_mode", False)) or bool(backend_override)
        if degraded:
            response.headers["X-Squire-Degraded-Mode"] = "true"

        # ---------------- Rail-block header (criterion #25) ----------------
        if _extract_nemo_block(state) is not None:
            response.headers["X-Squire-Rail-Blocked"] = "true"

        return _build_response(
            alert_id=alert_id,
            state=state,
            duration_ms=duration_ms,
            degraded_override_reason=degraded_reason_from_budget,
        )

    @app.post("/replay/{alert_id}")
    def replay_endpoint(
        alert_id: str,
        request: Request,
        response: Response,
        x_squire_token: str | None = Header(default=None, alias="X-Squire-Token"),
        x_internal: str | None = Header(default=None, alias="X-Internal"),
        x_squire_max_iters: str | None = Header(
            default=None, alias="X-Squire-Max-Iterations"
        ),
    ):
        _auth(x_squire_token, x_internal, request)
        stored = load_alert(alert_id)
        if stored is None:
            raise HTTPException(status_code=404, detail="alert_id not found")

        new_id = f"{alert_id}-replay-{uuid.uuid4().hex[:8]}"
        override_iters = _parse_max_iters(x_squire_max_iters)

        t0 = time.monotonic()
        state = _invoke_graph(stored, new_id, override_iters)
        duration_ms = int((time.monotonic() - t0) * 1000)

        try:
            save_investigation(
                new_id, state, duration_ms, alert_payload=stored, source="replay"
            )
        except Exception as e:  # pragma: no cover
            log.warning("replay persist failed for %s: %s", new_id, e)

        if state.get("_degraded_mode"):
            response.headers["X-Squire-Degraded-Mode"] = "true"

        return _build_response(alert_id=new_id, state=state, duration_ms=duration_ms)

    return app


app = create_app()
